### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by Anniepoo** [MarkusBernhardt/xml-doclet#7]
Running your doclet, and it's failing.

contents of dodoclet.sh:

CLASSPATH=../xml-doclet-1.0.6-jar-with-dependencies.jar;$CLASSPATH

javadoc -doclet com.github.markusbernhardt.xmldoclet.XmlDoclet -docletpath ../xml-doclet-1.0.6-jar-with-dependencies.jar -private -sourcepath %1 -d %2 Pengine

result:
2 warnings
~/kyndistuff/javalgt/scripts $./dodoclet.sh ../example/java ../example/docxml
invalid file (bad magic number): Exec format error
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Loading source files for package Pengine...
javadoc: warning - No source files for package Pengine
Constructing Javadoc information...
javadoc: warning - No source files for package Pengine
2 warnings
~/kyndistuff/javalgt/scripts $ls

I've tried this using the jar-with-dependencies from 
http://search.maven.org/remotecontent?filepath=com/github/markusbernhardt/xml-doclet/1.0.5/xml-doclet-1.0.5-jar-with-dependencies.jar

(linked to in your readme)
And in a freshly made jar (1.0.6, changed relevant references) made from sources.

I'm no Maven maven, but it looks like the dependencies are OK in the pom file?  

Any clue?

**Comment by MarkusBernhardt** [comment]
Hi,

this are actually two problems:

1. Logging
I'm using slf4j as logging API, but I cannot bundle a logging implementation to my libraries, because I cannot know, which logging framework (commons-logging, log4j, logbook) should be used. Therefore you get this three lines of errors:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

To avoid them, please add a slf4j logging implementation to the docletpah. Most easy would be slf4j-simple:
javadoc -doclet com.github.markusbernhardt.xmldoclet.XmlDoclet -docletpath xml-doclet-1.0.5-jar-with-dependencies.jar:slf4j-simple-1.7.12.jar

2 Package not found
This is the real problem. The javadoc executable does not find your package "Pengine"
Loading source files for package Pengine...
javadoc: warning - No source files for package Pengine
Constructing Javadoc information...
javadoc: warning - No source files for package Pengine
2 warnings

By default javadoc does not look for sub packages, so in your case only the package "Pengine" will be searched, and there are mo source files in.

But you can change that. Use parameter -subpackages.

**Comment by MarkusBernhardt** [comment]
Hi Anniepoo,
did this answer fix your problem or is there something I have to fix in the library?
Best regards,
Markus

**Comment by Anniepoo** [comment]
Yes, thanks.

**Comment by MarkusBernhardt** [comment]
Great!
Have fun.
